print(" ▄· ▄▌      ▄• ▄▌▄▄▄      ·▄▄▄▄  ▄▄▄ . ▄▄▄· ·▄▄▄▄")  
print("▐█▪██▌▪     █▪██▌▀▄ █·    ██▪ ██ ▀▄.▀·▐█ ▀█ ██▪ ██ ")
print("▐█▌▐█▪ ▄█▀▄ █▌▐█▌▐▀▀▄     ▐█· ▐█▌▐▀▀▪▄▄█▀▀█ ▐█· ▐█▌")
print(" ▐█▀·.▐█▌.▐▌▐█▄█▌▐█•█▌    ██. ██ ▐█▄▄▌▐█ ▪▐▌██. ██") 
print("  ▀ •  ▀█▄▀▪ ▀▀▀ .▀  ▀    ▀▀▀▀▀•  ▀▀▀  ▀  ▀ ▀▀▀▀▀•")
print("        _,.-------.,_")
print("     ,;~'             '~;, ")
print("   ,;                     ;,")
print("  ;                         ;")
print(" ,'                         ',")
print(",;                           ;,")
print("; ;      .           .      ; ;")
print("| ;   ______       ______   ; | ")
print("|  `/~'     ~' . '~     '~\'   |")
print("|  ~  ,-~~~^~, | ,~^~~~-,  ~  |")
print(" |   |        }:{        |   | ")
print(" |   l       / | \       !   |")
print(" .~  (__,.--'.^.  '--.,__)  ~. ")
print(" |     ---;' / | \ `;---     |  ")
print("  \__.       \/^\/       .__/  ")
print("    | \                 / |  ")
print("    | |T~\___!___!___/~T| |  ")
print("    | |`IIII_I_I_I_IIII'| |  ")
print("    |  \,III I I I III,/  |  ")
print("     \   `~~~~~~~~~~'    /")
print("       \   .       .   /")
print("         \.    ^    ./   ")

réponse = input("Veux tu rejouer ?")
while réponse != "oui" or réponse != "non" :
    réponse = input("Oui ou non ? ")
if réponse == "non" :
    System.exit (0)